const students = [
  { id: 1, name: "Sweden", image: "assets/flags/Sweden.jpg" },
  { id: 2, name: "Norway", image: "assets/flags/Norway.jpg" },
  { id: 3, name: "Denmark", image: "assets/flags/Denmark.jpg" },
  { id: 4, name: "Finland", image: "assets/flags/Finland.jpg" },
  { id: 5, name: "Germany", image: "assets/flags/Germany.jpg" },
  { id: 6, name: "France", image: "assets/flags/France.jpg" },
  { id: 7, name: "Spain", image: "assets/flags/Spain.jpg" },
  { id: 8, name: "Italy", image: "assets/flags/Italy.jpg" },
  { id: 9, name: "United Kingdom", image: "assets/flags/UnitedKingdom.jpg" },
  { id: 10, name: "Ireland", image: "assets/flags/Ireland.jpg" },
  { id: 11, name: "Netherlands", image: "assets/flags/Netherlands.jpg" },
  { id: 12, name: "Belgium", image: "assets/flags/Belgium.jpg" },
  { id: 13, name: "Switzerland", image: "assets/flags/Switzerland.jpg" },
  { id: 14, name: "Austria", image: "assets/flags/Austria.jpg" },
  { id: 15, name: "Portugal", image: "assets/flags/Portugal.jpg" },
  { id: 16, name: "Greece", image: "assets/flags/Greece.jpg" },
  { id: 17, name: "Poland", image: "assets/flags/Poland.jpg" },
  { id: 18, name: "Czech Republic", image: "assets/flags/CzechRepublic.jpg" },
  { id: 19, name: "Hungary", image: "assets/flags/Hungary.jpg" },
  { id: 20, name: "Romania", image: "assets/flags/Romania.jpg" },
];
